stages:
  train_mlflow:
    cmd: python src/train_with_mlflow.py
    deps:
      - src/train_with_mlflow.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    outs:
      - models/model.pkl
